### ISSUE TITLE
Style edit for Alarm language - generic thresholds made easy

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/rackspace-how-to#1065]
Hi @kmsholcomb, this article could really use your eyes. Even the title is a little strange!

https://support.rackspace.com/how-to/alarm-language-generic-thresholds-made-easy/

**Comment by kmsholcomb** [comment]
I'll look at it now, @stephamon

**Comment by kmsholcomb** [comment]
Hi @stephamon. The attached Word doc (and PDF copy) shows my suggested revision of the article. I did not use Track Changes, because that would have been too messy; I just revised it. Mainly, I think that the article just tries to describe the benefits of the alarm language in Rackspace Monitoring, so I just tried to revise it to do that. Make further revisions if you think they are needed. And please let me know if you have any questions. Thanks!

[alarm-language-rackspace-monitoring-KH.docx](https://github.com/rackerlabs/rackspace-how-to/files/309498/alarm-language-rackspace-monitoring-KH.docx)
[alarm-language-rackspace-monitoring-KH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/309499/alarm-language-rackspace-monitoring-KH.pdf)
