### ISSUE TITLE
Full audit: Manually configure Android devices for email hosted on Exchange 2013

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#1436]
Full audit needed.

https://github.com/rackerlabs/rackspace-how-to/blob/3a1798e3176cb5f98dd53154ec38a9de95d74f06/content/exchange/manually-configure-android-devices-for-email-hosted-on-exchange-2013.md

This article ranks 18 in most viewed articles.

**Comment by stephamon** [comment]
- [ ] SME check
- [ ] Editor check
- [ ] update `audit_date`

**Comment by stephamon** [comment]
Emailed Cody on 09/12.

**Comment by stephamon** [comment]
@kmsholcomb Can you give this article a pass through? https://support.rackspace.com/how-to/manually-configure-android-devices-for-email-hosted-on-exchange-2013/

**Comment by kmsholcomb** [comment]
@stephamon  I'll do it first thing in the morning.

**Comment by kmsholcomb** [comment]
Hi @stephamon. My edits are in the attached Word doc (and PDF copy of it). I suggest a bit of rearrangement at the beginning, so that the article doesn't start with a note, and the prereq is called out a little more clearly. Otherwise, it's just basic copy edits. Please let me know if you have any questions. Thanks! 

[Manually configure Android devices for email hosted on Exchange 2013_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/470215/Manually.configure.Android.devices.for.email.hosted.on.Exchange.2013_editsKH.pdf)
[Manually configure Android devices for email hosted on Exchange 2013_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/470214/Manually.configure.Android.devices.for.email.hosted.on.Exchange.2013_editsKH.docx)
