### ISSUE TITLE
Broken links on Rackspace.com/support

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#1461]
Links within the "Account Selection" portion of the URL Rackspace.com/support do not appear to work as intended. When clicking on the 3 options (Cloud, Dedicated servers, Email) the page does not correctly redirect the user to the links further down the page.

**Comment by meker12** [comment]
Hello  -- 

If you add a slash before the #cloud, the links goes to the page location instead of generating a 404.

https://www.rackspace.com/support/#cloud
https://www.rackspace.com/support/#dedicated
https://www.rackspace.com/support/#email

The syntax above goes to a location identified by an id instead of an anchor ref.  In the source for the each section, the location is identified by an ``id`` attribute not an ``a href``. See [Links in HTML](https://www.w3.org/TR/html4/struct/links.html#h-12.2.1)

The links above don't go to the title because the id is on the div tag.  It should be on the header tag (``h2`` in this case).   

Page source for section heading:
```      
<p class="center"><p class="center"><a href="#cloud">Cloud</a></p>
<p class="center"><a href="#dedicated">Dedicated Servers</a></p>
<p class="center"><a href="#email">Email</a></p></p>
```

There is an extra </p> at end of last link.

Here are the div classes for each section:
```
<div class="col-md-12">
        <h2 class="center pattern-header">          <div class="text-center">Cloud Support<span id="cloud" class="offset"></span></div>        </h2>      </div>
```

```
<div class="col-md-12">
        <h2 class="center pattern-header">          <div class="text-center">Dedicated Server Support<span id="dedicated" class="offset"></span></div>        </h2>  
```

````
<div class="col-md-12">
        <h2 class="center pattern-header">          <div class="centered">Email Support<span id="email" class="offset"></span></div>            </h2>
````

You can see the correct syntax on the API docs landing page, for example, go to the following link for RPC docs:

https://developer.rackspace.com/docs/#docs-private-cloud


When you get to that page, do a view source and search on ``docs-private-cloud`` to see the html markup:

```
<div class="card-content">
                    <div class="card-title">
                        <h4 id="docs-private-cloud">Rackspace Private Cloud powered by OpenStack</h4>
                    </div>
```
*Fix:*

- [ ] Change the links on each section to add the ``/`` before the location reference.

- [ ] Update the HTML for the page, or the css if the page is generated, so that the id is on the header tag
       instead of the div tag.

**Comment by meker12** [comment]
Possibly related issue: https://github.com/rackerlabs/nexus-control/issues/492

**Comment by ReneeRendon** [comment]
As @stephamon pointed out, this is not part of support site that we maintain. Because the URLs are so similar, I didn't even realize that until she pointed it out. 

**There are a few additional issues to address on this page as well.**

1.  Under Support on the top navigation bar in the the drop down menu, it should say How-To instead of Knowledge Center.

2. At the bottom of the page under Community and Forums, it should say How-To instead of Knowledge Center, and the link should say support.rackspace.com/how-to.

3. At the bottom under API Documentation, it should take you to https://developer.rackspace.com/docs/.

4. Under Exchange Support, the link should say support.rackspace.com/how-to/exchange.

5. Should Cloud Sites still be listed under Cloud Support?

6. In the footer, the link to the API docs should go to: https://developer.rackspace.com/docs/.

**Comment by meker12** [comment]
I wondered about that.  support.rackspace.com is [controlled from Nexus](https://github.com/rackerlabs/nexus-control/blob/master/config/content.d/support.rackspace.com.json).  Not sure who works on the content.

**Comment by ReneeRendon** [comment]
This ticket has been opened on the WebDev JIRA board now.
