### ISSUE TITLE
Full audit: Add another Wordpress site to an existing Cloud Orchestration stack

### ISSUE THREAD

**Issue by DonNateR** [rackerlabs/rackspace-how-to#1576]
https://github.com/rackerlabs/rackspace-how-to/blob/master/content/cloud-orchestration/add-another-wordpress-site-to-an-existing-cloud-orchestration-stack.md

Each step must be performed in order for an article to be considered audited:

- [ ] SME check: Update any out of date or inaccurate technical content with the help of a SME
- [ ] Editor check: Incorporate edits from Kelly Holcomb
- [ ] Quality Checklist: Perform a quality audit of the article using the quality checklist - https://docs.google.com/a/gapps.rackspace.com/forms/d/e/1FAIpQLScRRF4MzJjdeAOvQTabKSyNysRaS5FW7ot3uPtZLPAlUrG0Ug/viewform?c=0&w=1
- [x] Update audit_date: Update the `audit_date` metadata in the article with the date of the full audit's completion

See issue #1423  for more information.

**Comment by catlook** [comment]
Response from James Low:  It looks like the article is out of date here compared to how our orchestration stack is currently building things.
 
1.       The KB tells us to configure MySQL to allow access for the additional WordPress website by adding another database and user however, the current orchestration uses our DBaaS offering and thus this should be done via our MyCloud portal (or equivalent API commands) and not MySQL commands.
 
Additionally, those commands would only work if root access was enabled for the DBaaS instance in question and this is not the default.
 
2.       The KB is written with Apache in mind with regards to the configuration of the web server however, we appear to be using nginx now and thus all configuration is different here.
 
3.       Due to point 2, we now need to use PHP FPM. Whilst the same pool can be used for additional websites, it helps to create separate pools for each website to provide easier control over how much resources each additional website can use. This typically depends on the use case though so might not be suitable for all. The current naming scheme being used would become a misnomer though (eg. the PHP FPM pool and error logs all use example.com (or whatever the initial site was named) and additional sites would also use example.com which could initially confuse people).
 
PHP FPM has also been configured to use TCP instead of sockets which is significantly slower though that would be for the orchestration template maintainer to fix.
 
4.       We have 2 orchestration templates; one for CentOS and one for Ubuntu and both come with their little quirks on where they store configuration files. For example, CentOS stores all active nginx website configuration files in /etc/nginx/conf.f but Ubuntu stores them in /etc/nginx/sites-available and then symlinks them to /etc/nginx/site-enabled to make them active. This also means that some instructions in the KB like using apt-get will not work because CentOS uses yum.
 
Ultimately, it looks like the article would need a complete rewrite to be current with  our orchestration

**Comment by catlook** [comment]
Retiring article  for now.

**Comment by catlook** [comment]
closed with pr #1617
