### ISSUE TITLE
Full audit: Accelerating Wordpress with cloud files

### ISSUE THREAD

**Issue by DonNateR** [rackerlabs/rackspace-how-to#1579]
https://github.com/rackerlabs/rackspace-how-to/blob/master/content/cloud-files/accelerating-wordpress-with-cloud-files-cdn-and-the-w3-total-cache-plugin.md

Each step must be performed in order for an article to be considered audited:

- [ ] SME check: Update any out of date or inaccurate technical content with the help of a SME
- [ ] Editor check: Incorporate edits from Kelly Holcomb
- [ ] Quality Checklist: Perform a quality audit of the article using the quality checklist
- [ ] Update audit_date: Update the `audit_date` metadata in the article with the date of the full audit's completion

See issue #1423  for more information.

**Comment by RobinJoe** [comment]
30/11 - I have an update on this one, I've been going over James L.'s SME review, and to improve the article it needs:
1. Rewriting the introduction to remove cloudfiles, and explain that Rackspace CDN is available following the information James wrote in the onewiki article - https://one.rackspace.com/pages/viewpage.action?title=CDN&spaceKey=Linux

2. Adjust the $ sudo chmod go+w command , or change the procedure, so that the article does not recommend global write permssions on the wp-content directory.

I can continue work, and attempt to update the article using the one wiki article.

**Comment by DonNateR** [comment]
Thanks for the update @RobinJoe. Let me know if you need any help with this.

**Comment by DonNateR** [comment]
@RobinJoe: Will try to test the steps himself. If he can't, he'll pass the audit on to the How-To team

**Comment by ReneeRendon** [comment]
@RobinJoe Any update on this?

**Comment by RobinJoe** [comment]
I have an update on the issue so far, and the next step:

- Cloud Files is no longer used as a content delivery network. Rackspace has a CDN works as an alternative
- I followed SME James Low’s procedure - https://one.rackspace.com/pages/viewpage.action?title=CDN&spaceKey=Linux
- James suggested that the procedure is fine to adapt from Magento to Wordpress. Instance of ‘media’ in the article can change to ‘wordpress’
- After making some changes based on the wiki article, I attempted to test the procedure using a mycloud wordpress server, however I had issues logging into the server back end.

If anyone is able to pick up the testing, or knows an SME who can test, feel free to take this one on.

**Comment by ReneeRendon** [comment]
Check pageviews and find a new SMEs.

**Comment by stephamon** [comment]
@ReneeRendon there have been 960 views on this article since July. Judging from the title, it sounds pretty similar to the article I've been working on: "Configure W3 Total Cache for WordPress with Cloud Files and CDN."

I can go ahead and claim this one and investigate whether we need both of them.

**Comment by stephamon** [comment]
Okay. This seems to be basically the same as the "Configure W3TC" article, but with an additional component on optimizing the site performance. I think I can add that part into a new section on the other article and then we won't have to have this one.
