### ISSUE TITLE
Update instructions in Reboot your server

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/rackspace-how-to#1733]
Can this article be edited, specifically this part Windows
Issue a restart request by clicking Start > Shut down.
If we can add >select restart from the dropdown,  to the end of that then it would be more clear. I have had 3 customers in the last week say they followed the article and the server never came back up. 
 
https://support.rackspace.com/how-to/reboot-your-server/

**Comment by stephamon** [comment]
Basically, in the "Perform a soft reboot" section, under the Windows instructions, change "Issue a restart request by clicking **Start > Shut down**" to "Issue a restart request by clicking **Start > Shut down > Restart**", I think.

**Comment by nimbinatus** [comment]
I think it's more like this image from Windows 7:
![windows-7-start-menu](https://cloud.githubusercontent.com/assets/1538692/21623429/f22f48b4-d1c7-11e6-80c9-bdda5efdc6e0.jpg)
Going to run with it, anyway, and pass it to an SME to be sure.

**Comment by nimbinatus** [comment]
From: Sean
Date: Wednesday, January 4, 2017 at 10:39 AM
To: Laura
 
That looks a lot better, it’s very clear and I think this will help out a lot.
Under the perform a soft reboot you can delete this, Note: OS reboots, such as the sudo reboot shown below, do not trigger the FG2NG migration.
We are finished with 1st gen migrations so that isn’t relevant anymore.

 ------------------------------------------------
From: Laura
Date: Wednesday, January 4, 2017 at 10:34 AM
To: Sean

Mind checking me real quick? https://staging.developer.rackspace.com/support.rackspace.com/build-28c718468a/how-to/reboot-your-server/
....

 ------------------------------------------------
From: Sean
Date: Wednesday, January 4, 2017 at 9:55 AM
To: Laura
 
Option 2.

Option 1 is the command line reboot option and that would be good to put in the article as well.
...

 ------------------------------------------------
From: Laura
Date: Wednesday, January 4, 2017 at 9:49 AM
To: Sean

Sean,
I am working on cleaning up the article in question, and I want to ensure I word the adjustment properly. Which option does the restart menu look more like: option 1 (Windows Server 2012) or option 2 (Windows Server 2012 R2)?
1. ![image001](https://cloud.githubusercontent.com/assets/1538692/21650797/cddd91ec-d26b-11e6-89a5-667d79b57ed4.png)

2. ![image002](https://cloud.githubusercontent.com/assets/1538692/21650807/d42490a0-d26b-11e6-8189-700b9d45bd1d.png)

...
