### ISSUE TITLE
Update article: Transferring your DNS hosting to Rackspace

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#2144]
The following update has been suggested. Please see the how-to email sent July 3 at noon for more detailed information.

To ensure a seamless transition with minimal service interruption, you should duplicate the DNS records from your current host into the Rackspace Cloud Control Panel before changing nameservers.  This can be accomplished using the following steps:
 
1. Log into your Rackspace Cloud Control Panel, choose Networking from the options at the top, and click on Cloud DNS in the menu that drops down.
2. On the Cloud DNS page, click on Create Domain.  Enter the domain you are adding along with an administrative email address that will be publicly associated with the domain.  We recommend leaving the TTL at the default of five minutes.  Click Create Domain to save the information and create the domain.
3. This should open the Domain Details page.  Here, you can click Add Record and begin entering your DNS records.  Choose the record type then provide the information requested.  Again, we recommend leaving the TTL at the default of five minutes.  Choose Add Record to save the new record.
4. Continue adding any other records to match your existing DNS host.  If you enter the same records with the same information as listed with your original DNS host, as the name server change propagates end users will get the same answer whichever DNS host they are querying.
5. Log into your domain registrar’s control panel and change the NS servers for your domain to:
dns1.stabletransit.com
dns2.stabletransit.com
 
Following these steps will initiate the process to switch DNS hosting to Rackspace, but the changes may take up to 48 hours to propagate.  If you want to change any DNS records (such as moving an A record to point to your Rackspace cloud server), you either need to make the change on both DNS hosts, or wait until the changes have propagated worldwide.
 
Making these changes will redirect all DNS queries to Rackspace, but does not affect the registration of your domain.  You will need to maintain your registration with the original registrar.

https://support.rackspace.com/how-to/transferring-your-dns-hosting-to-rackspace/

**Comment by catlook** [comment]
Can you paste the this email here?  The how-to email sent July 3 at noon with more detailed information.

I tend not to keep emails that don't apply to me.

**Comment by catlook** [comment]
Email from July 3rd, forwarded to us by Addison Martinez:

From: Sameer Kotasthane 
Sent: Friday, June 30, 2017 3:55 PM
To: Jason Hammons <jason.hammons@RACKSPACE.COM>; Mikel Mendoza <mikel.mendoza@rackspace.com>; Addison Martinez <addison.martinez@RACKSPACE.COM>
Cc: Trent Gillaspie <trent.gillaspie@RACKSPACE.COM>
Subject: RE: DNS hosting with Rackspace
 
Moving William to BCC
+ Addison, would you be able to update the link below with the instructions that James drafted for us in email below?
https://support.rackspace.com/how-to/transferring-your-dns-hosting-to-rackspace/
 
Thanks, sameer
 
Sameer Kotasthane
Product Manager – Public Cloud
Cell: (512)940-4935
 
From: Jason Hammons 
Sent: Friday, June 30, 2017 2:17 PM
To: Sameer Kotasthane <Sameer.Kotasthane@rackspace.com>; Mikel Mendoza <mikel.mendoza@rackspace.com>
Cc: Trent Gillaspie <trent.gillaspie@RACKSPACE.COM>; William Loy <William.Loy@rackspace.com>
Subject: Re: DNS hosting with Rackspace
 
Sameer,
 
I apologize for the delay, I’ve been working on this in between tickets and calls.  Let me know what you think.
 
----------------------------------------------------
 
Rackspace Cloud is not a domain registrar like GoDaddy, Tucows, or NameCheap. In order to host your domain with Rackspace DNS, you will need to have already registered your domain with a valid registrar and changed the name servers the registrar has associated with your domain to point to the Rackspace nameservers.  When changing nameservers with your registrar, be sure to plan ahead as it can take up to 48 hours for this change to take effect worldwide.
 
To ensure a seamless transition with minimal service interruption, you should duplicate the DNS records from your current host into the Rackspace Cloud Control Panel before changing nameservers.  This can be accomplished using the following steps:
 
Log into your Rackspace Cloud Control Panel, choose Networking from the options at the top, and click on Cloud DNS in the menu that drops down.
On the Cloud DNS page, click on Create Domain.  Enter the domain you are adding along with an administrative email address that will be publicly associated with the domain.  We recommend leaving the TTL at the default of five minutes.  Click Create Domain to save the information and create the domain.
This should open the Domain Details page.  Here, you can click Add Record and begin entering your DNS records.  Choose the record type then provide the information requested.  Again, we recommend leaving the TTL at the default of five minutes.  Choose Add Record to save the new record.
Continue adding any other records to match your existing DNS host.  If you enter the same records with the same information as listed with your original DNS host, as the name server change propagates end users will get the same answer whichever DNS host they are querying.
Log into your domain registrar’s control panel and change the NS servers for your domain to:
dns1.stabletransit.com
dns2.stabletransit.com
 
Following these steps will initiate the process to switch DNS hosting to Rackspace, but the changes may take up to 48 hours to propagate.  If you want to change any DNS records (such as moving an A record to point to your Rackspace cloud server), you either need to make the change on both DNS hosts, or wait until the changes have propagated worldwide.
 
Making these changes will redirect all DNS queries to Rackspace, but does not affect the registration of your domain.  You will need to maintain your registration with the original registrar.
 
References: Create DNS Records for cloud servers with the Control Panel
 
--------------------------------------------------------------
 
 
From: Sameer Kotasthane <Sameer.Kotasthane@rackspace.com>
Date: Friday, June 23, 2017 at 5:13 PM
To: Jason Hammons <jason.hammons@RACKSPACE.COM>, Mikel Mendoza <mikel.mendoza@rackspace.com>
Cc: Trent Gillaspie <trent.gillaspie@RACKSPACE.COM>, William Loy <William.Loy@rackspace.com>
Subject: RE: DNS hosting with Rackspace
 
Thanks Jason, that would help.
Sincerely, sameer
 
From: Jason Hammons 
Sent: Friday, June 23, 2017 4:37 PM
To: Sameer Kotasthane <Sameer.Kotasthane@rackspace.com>; Mikel Mendoza <mikel.mendoza@rackspace.com>
Cc: Trent Gillaspie <trent.gillaspie@RACKSPACE.COM>; William Loy <William.Loy@rackspace.com>
Subject: Re: DNS hosting with Rackspace
 
Well, at a minimum you have to create the zone and add an A record or two, unless this has already been done.  Not all zones have CNAME or MX (mail) records. I agree that the three-step page could use a lot more detail, as it is there’s almost nothing of substance there.  We could provide mid-level instructions on the three-step page (log into the control panel, access the Cloud DNS page under Networking, create your domain and add records to correspond with your existing DNS provider, etc.) and provide the more detailed page as a resource at the bottom.  I’m just looking for a way to balance reducing clicks with overloading a single page with too much information.
 
If you think this would work, I could write up something in between on detail and you can see how that would look.
 
From: Sameer Kotasthane <Sameer.Kotasthane@rackspace.com>
Date: Thursday, June 22, 2017 at 2:45 PM
To: Mikel Mendoza <mikel.mendoza@rackspace.com>
Cc: Trent Gillaspie <trent.gillaspie@RACKSPACE.COM>, William Loy <William.Loy@rackspace.com>, Jason Hammons <jason.hammons@RACKSPACE.COM>
Subject: RE: DNS hosting with Rackspace
 
Thanks Jason and Mikel. I agree that Cloud DNS instructions flow much better on: https://support.rackspace.com/how-to/serving-your-domain-from-a-rackspace-cloud-server/
But I think that the 3-step process described on this link should NOT link to another page for Step1. In the interest of minimizing clicks for users, is there perhaps a way to pull just the core subset of instructions from this page back onto the Step 1 in link above? Or do users always have to create a DNS zone for their domain, then add A, CNAME and MX record in each case?
Thanks, sameer
 
Sameer Kotasthane
Product Manager – Public Cloud
Cell: (512)940-4935
 
From: Mikel Mendoza 
Sent: Thursday, June 22, 2017 2:24 PM
To: Sameer Kotasthane <Sameer.Kotasthane@rackspace.com>
Cc: Trent Gillaspie <trent.gillaspie@RACKSPACE.COM>; William Loy <William.Loy@rackspace.com>; Jason Hammons <jason.hammons@RACKSPACE.COM>
Subject: Re: DNS hosting with Rackspace
 
Hi Sameer.
 
I asked my Linux Tech, Jason Hammons, to assist.  I’ve added him to this thread.  Here is his feedback:
 
“I’m not sure how it works on the dedicated side, but it’s very different for cloud.  As far as I know, we don’t charge for Cloud DNS, and there’s no requirement that a Racker be involved with getting DNS set up.  It’s also very definitely not automatic.  There is a way you can import an entire zone into DNS, but I’m not sure if most support Rackers know about this, and we have to have the zone file to import.  It used to be possible to request all records for a given domain from DNS servers, but best practices are to not allow this for security reasons, so many DNS servers won’t respond properly if you request the entire zone.
 
We also use different DNS servers for cloud vs. dedicated, so step 2 needs to be updated as well.  Really, we probably just need 2 separate documents for dedicated or cloud.  I’m not sure where that particular page comes from, but I found this page linked from the DNS page in Reach: https://support.rackspace.com/how-to/serving-your-domain-from-a-rackspace-cloud-server/.  While a little oversimplified in some respects (“Use the Rackspace Cloud Control Panel to create corresponding DNS records for your domain”), it’s much more appropriate to Cloud DNS.  It would be nice if it also linked to an article with more instructions like https://support.rackspace.com/how-to/create-dns-records-for-cloud-servers-with-the-control-panel/ and possibly reference contacting us, maybe something like:
 
Use the Rackspace Cloud Control Panel to create corresponding DNS records for your domain using instructions athttps://support.rackspace.com/how-to/create-dns-records-for-cloud-servers-with-the-control-panel/, or contact your support team if you need assistance.
 
If it’s done properly, there shouldn’t be any service interruption.  Basically, we need to duplicate their existing records so that everyone gets the same answers whether they’re asking the old host or our servers while the registrar updates the information.  It doesn’t matter if you’re looking in last year’s phone book or this year’s, as long as the phone number is the same.”
 
Please let us know if there are additional questions.
 
Thank you.
 
Mikel
 
 
From: Sameer Kotasthane <Sameer.Kotasthane@rackspace.com>
Date: Tuesday, June 20, 2017 at 3:45 PM
To: Mikel Mendoza <mikel.mendoza@rackspace.com>
Cc: Trent Gillaspie <trent.gillaspie@RACKSPACE.COM>, William Loy <William.Loy@rackspace.com>
Subject: DNS hosting with Rackspace
 
Hi Mikel, William reached out asking about this link: https://support.rackspace.com/how-to/transferring-your-dns-hosting-to-rackspace/
 
Step 1 states "Contact our support team and request the DNS Hosting service for your domain. At this time, we will automatically set up your DNS according to your current DNS settings, ". I understand that our DNS hosting transfer work flow requires DNS records to be manually configured in the zone prior to pointing name servers to Rackspace. It is not an automatic process, and unfortunately, I don’t know whether there is any service interruption.
 
Could you confirm how this works for Cloud Servers? And would you suggest any updates to the instructions in link above?
 
Thkx, sameer
Sameer Kotasthane
Product Manager – Public Cloud
Cell: (512)940-4935

**Comment by catlook** [comment]
Flagging as full audit since content is completely updated by SMEs.  Will get them to take one last look.

**Comment by catlook** [comment]
Sent to kelly for edit
