### ISSUE TITLE
Bug in search results

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#484]
1. On https://support.rackspace.com/how-to/, type ​*kernel*​ into the Search box. 
2. Limit the results to How-To.
3. At the bottom of the result list, click ​*Load more results*​.
4. After you click that button once or twice, the results list starts to show duplicate results.

At some point, after all the results of the search have been loaded, that ​*Load more results*​ button should probably go away, or be unclickable.

**Comment by stephamon** [comment]
@ReneeRendon So, from what I understand, Steve's team used a custom Google search to pull in the search box results for support.rackspace. This was to make sure that the community posts would be grabbed also.

The downside is that I don't know what account they used to make custom search, because the Docs team Google account is not it. We'll need to find out what account they used and get access to it.

**Comment by ReneeRendon** [comment]
This behavior is still occurring.

**Comment by ReneeRendon** [comment]
Ken's team has fixed this bug.

**Comment by kmsholcomb** [comment]
Ha! I'll let Jered know. He was the one that "reported" this bug, months ago. :)
