### ISSUE TITLE
"Detailed invoices overview" needs updated screenshots

### ISSUE THREAD

**Issue by DonNateR** [rackerlabs/rackspace-how-to#522]
Hello Team,

Heads up - The Billing and Payments page in REACH is going to be changing soon to allow for multiple Credit card and ACH payments. As a result the first screenshot in : https://www.rackspace.com/knowledge_center/article/detailed-invoices-overview will have to be updated. Reach links to this URL in the side bar and it would be nice to have the page updated around release time. The changes on the page are highlighted in this screen capture: http://screencast.com/t/qz0LZbwQ .

Nicole Schwartz should be able to get you more information around release timelines and changes being made.

Thank you,
Arthi

**Comment by DonNateR** [comment]
Billing interface has yet to be updated.

**Comment by ReneeRendon** [comment]
On the how to make payments/update payment methods the screens look new and now support CC and ACH (echeck)
This is from Nicole: 

So if you login to any prod account and go to the following links to see the pages
 
https://mycloud.rackspace.com/account#payments/one-time instead of pop over
 
https://mycloud.rackspace.com/account#payments/manage for US only - replaces the current “add new CC which replaces old CC” flow, now you can have many credit cards (and ACH accounts) on file and this is where you can manage them. UK still using 1 CC only flow.
 
All else the same really
