### ISSUE TITLE
Create Managed DNS FAQ

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#595]
[Managed DNS (EA) FAQ_FINAL.docx](https://github.com/rackerlabs/rackspace-how-to/files/161866/Managed.DNS.EA.FAQ_FINAL.docx)

**March 14 is EA launch day for Managed DNS.**

- This Managed DNS, FAQ page needs to be added to the Cloud DNS section of the How-To on 3/14.

- The link that has been assigned to it is https://support.rackspace.com/how-to/managed-dns-faq/.

- The title must be managed-dns-faq.md

- The FAQ has been approved by legal already.

- We need Kelly to check it over before publishing on 3/14. @kmsholcomb

**Comment by kmsholcomb** [comment]
Hi @ReneeRendon. My edits are in the attached Word doc (and PDF copy of it). Please let me know if you have any questions. 

@catlook: One of the questions in this FAQ, about the differences between Managed DNS and Cloud DNS, has a list of features that is similar to what appears in the v2 API release notes. I made a couple slightly different edits in the attached doc, and I'd like for you to consider those for the RN edits, instead of what I sent you with the API edits. If you have any questions, please let me know. 

[Managed.DNS.EA.FAQ_FINAL_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/163835/Managed.DNS.EA.FAQ_FINAL_editsKH.pdf)
[Managed.DNS.EA.FAQ_FINAL_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/163836/Managed.DNS.EA.FAQ_FINAL_editsKH.docx)
