### ISSUE TITLE
Update White Paper: Architecting Linux Environments

### ISSUE THREAD

**Issue by DonNateR** [rackerlabs/rackspace-how-to#600]
-----Original Message-----
From: Dave Coon
Sent: Monday, March 7, 2016 3:20 PM
To: Stuart Bankey <stuart.bankey@rackspace.com>
Subject: Article is correct but incorrect.

Stuart,

This article
https://support.rackspace.com/white-paper/architecting-high-availability-linux-environments-within-the-cloud/
refrences things that were capable of being done in our First Generation servers but is no long capable in our next generation servers. Who can I contact to get this article updated?

--
If you have any other questions/comments/concerns please let us know.

Thanks!
Dave Coon
Cloud Virtualization Engineer I
US Toll Free: 1.855.348.9062
International: +1.210.581.0407
https://support.rackspace.com

**Comment by stephamon** [comment]
Reaching out to Dave Coon

**Comment by stephamon** [comment]
Stephaine,

If we do not pull it down now, the best thing to do would be to put in
the article the following just below the summary:

DISCLAIMER: THIS ARTICLE ONLY APPLIES TO FIRST GENERATION SERVERS. WE
ARE CURRENTLY WORKING ON SHARED VIRTUAL IP'S IN OUR NEXT GENERATION
INFRASTRUCTURE BUT DO NOT HAVE A PLANNED PUBLIC RELEASE DATE.

or something to that effect. But I honestly recommend pulling it down
because less than 1% of all customers have used this technology.

If you have any other questions/comments/concerns please let us know.

Thanks!
Dave Coon
Cloud Virtualization Engineer I
US Toll Free: 1.855.348.9062
International: +1.210.581.0407
https://support.rackspace.com

On 03/09/2016 09:17 AM, Stephanie Fillmon wrote:
Hey Dave,

It’s definitely no problem to retire it. Do you think it would be best to pull it down now or wait until First Gen Servers are officially gone?

Stephanie




On 3/9/16, 9:12 AM, "Dave Coon" <davide.coon@RACKSPACE.COM> wrote:

Stephanie,

Honestly the article needs to go away, as this pertains 100% to First
Generation servers and we are in the progress of getting rid of all of
our First Generation Servers. By the end of the summer, there will be
none left. Would it be an issue to just remove the article?

If you have any other questions/comments/concerns please let us know.

Thanks!
Dave Coon
Cloud Virtualization Engineer I
US Toll Free: 1.855.348.9062
International: +1.210.581.0407
https://support.rackspace.com

**Comment by stephamon** [comment]
fixes https://github.com/rackerlabs/rackspace-white-paper/pull/17
