### ISSUE TITLE
Permalink missing Contributing.md metadata

### ISSUE THREAD

**Issue by DonNateR** [rackerlabs/rackspace-how-to#731]
Now that URL's us permalinks, we need to make sure that permalink's, and instructions on how to name a permalink, are including in the [Contribution Guidelines](https://github.com/rackerlabs/rackspace-how-to/blob/master/CONTRIBUTING.md). 

Remember, for SEO purposes, the permalink should match the title name.

**Comment by kmsholcomb** [comment]
For Carina, we created a separate file that explained all the frontmatter metadata. You might consider creating something like that, which you could link to from the Contributor guidelines, if you don't want to make that file to get too much longer. The Carina file is here: https://github.com/getcarina/getcarina.com/blob/master/frontmatter-metadata-guidelines.md. 

(You can't really reuse the permalink guidelines from that file, because permalinks are formed differently in Carina,  but maybe some of the information could be borrowed.)

**Comment by ReneeRendon** [comment]
Once we have added the permalink information, we need to link to it from this internal wiki page under the Process section.
https://one.rackspace.com/display/devdoc/How-To+team+processes

**Comment by DonNateR** [comment]
https://github.com/rackerlabs/rackspace-how-to/pull/736

**Comment by kylelaffoon** [comment]
Added anchor in the Contributing.md file for link from https://one.rackspace.com/display/devdoc/How-To+team+processes . Linked Permalink and Metadata references.
