### ISSUE TITLE
Add SERVICENETENABLED=1 to Cloud Backup Installation article

### ISSUE THREAD

**Issue by cyrichardson** [rackerlabs/rackspace-how-to#947]
From IRC convo for https://support.rackspace.com/how-to/rackspace-cloud-backup-install-the-agent-on-windows-by-using-silent-installation/

09:56 atl-bot: <brett.johnson> SERVICENETENABLED=1
09:56 atl-bot: <brett.johnson> SCO_bmetzler @slacker_bmetzler ^ ^ ^ ^ ^]
09:56 atl-bot: <brett.johnson> did we forget to put that in the documentation i'm guessing?
10:01 atl-bot: <slacker_bmetzler> brett.johnson: yep.  Updating the internal wiki page on that.

10:06 catherine: slacker_bmetzler: So not an external doc thing for the above?
10:07 atl-bot: <slacker_bmetzler> cath6184: there is one place where that is shown externally.  The Silent install page.
10:07 atl-bot: <brett.johnson> @cath6184: if that is not in the installer docs we definitely need to add it
10:07 atl-bot: <brett.johnson> catherine: ^ ^ ^
10:08 atl-bot: <slacker_bmetzler> cath6184: https://support.rackspace.com/how-to/rackspace-cloud-backup-install-the-agent-on-windows-by-using-silent-installation/
10:13 catherine: Thanks! I'll open an issue on the How-to docs for that and I'll send the issue number to you shortly.

**Comment by brett-johnson** [comment]
Set SERVICENETENABLED=1 to force an agent to never use public addresses for backup operations. If we fail over to public addresses for communication to Rackspace APIs, this will incur charges for the customer. Some customers prefer not to do backups, rather than fail over to public IP addresses where they can incur charges for backups.
